### ISSUE TITLE
Maybe it's a bug that lets external contracts call, causing the loss of the token pool

### ISSUE THREAD

**Issue by gguoss** [pontem-network/liquidswap#114]
https://github.com/pontem-network/liquidswap/blob/c360ff1c3328581a0c78ed3f74a1c53acd9bfbd3/sources/swap/liquidity_pool.move#L368

**Comment by borispovod** [comment]
Can you explain please?

The returned `Flashloan` object should be always returned back with `pay_flashloan`, so you can't just extract funds.

**Comment by gguoss** [comment]
clear, Thank you
