### ISSUE TITLE
Liquidswap address

### ISSUE THREAD

**Issue by 0xPhoenix9** [pontem-network/liquidswap#117]
Hello.
I am a developer who use aptos network.
And I had an problem in publishing after new version of devnet released.

In github Move.toml file, liquidswap address is set as following:
[addresses]
liquidswap = "0x190d44266241744264b964a37b8f09863167a12d3e70cda39376cfb4e3561e12"
but i can't find that address in aptos devnet explorer.

Please fix this problem so that I can use liquidswap dependency.

thanks

**Comment by borispovod** [comment]
Hey @0xPhoenix9 ,

We currently deployed to testnet. 
We will deploy for devnet in the near time.

**Comment by 0xPhoenix9** [comment]
hi @borispovod 

thanks for your reply and kindness.

pls deploy to devnet asap and let me know.
I am waiting for your response.

thanks again

**Comment by naiba** [comment]
You can temporarily use routerV1 (devnet branch) on the testnet to test

https://explorer.aptoslabs.com/account/e951645e2d0f85a1695bd78a7319fe259136dcdb7833bfed893c8912b5385889?network=testnet

**Comment by borispovod** [comment]
Router v2 deployed on testnet. We are currently discussing deployment on devnet, but it would probably take additional time and contain different addresses.

**Comment by borispovod** [comment]
The testnet version has been deployed on same addresses, include all routers.
Dapp is also available - testnet.liquidswap.com 

For devnet we probably would deploy on another address soon.

**Comment by borispovod** [comment]
Devnet version is available and should be updated each time Aptos redeploy devnet. 

You can look at branch [devnet-addresses](https://github.com/pontem-network/liquidswap/tree/devnet-addresses).
Test coins addresses are same (like on testnet), dependencies have their own devnet-addresses branch.

Closing it.
