### ISSUE TITLE
Do I need to initialize the liquidity pool or the lp account after contracts are published?

### ISSUE THREAD

**Issue by y0unghe** [pontem-network/liquidswap#125]
I am trying to register a liquidity pool but can't get it to work. Do I need to initialize the liquidity pool or the lp account for the first time after all the contracts are published? Do any pool preparation or functions need to be called before I can register a liquidity pool and add some liquidities to the pool?

**Comment by borispovod** [comment]
Hey, 

In case of liquidswap mainnet/testnet no, you just have to call register function. 

Regarding your own private network, yes, but only one time to initialize liquidswap itself.
