### ISSUE TITLE
[Question] convert move struct LiquidityPool to Rust struct

### ISSUE THREAD

**Issue by crazybits** [pontem-network/liquidswap#128]
how can i convert  the following Pontem liquidity move struct to Rust
any sample for reference？so i can convert this resource to Rust struct.

```
struct LiquidityPool<phantom X, phantom Y, phantom Curve> has key {
        coin_x_reserve: Coin<X>,
        coin_y_reserve: Coin<Y>,
        last_block_timestamp: u64,
        last_price_x_cumulative: u128,
        last_price_y_cumulative: u128,
        lp_mint_cap: coin::MintCapability<LP<X, Y, Curve>>,
        lp_burn_cap: coin::BurnCapability<LP<X, Y, Curve>>,
        // Scales are pow(10, token_decimals).
        x_scale: u64,
        y_scale: u64,
        locked: bool,
        fee: u64,           // 1 - 100 (0.01% - 1%)
        dao_fee: u64,       // 0 - 100 (0% - 100%)
    }
```

**Comment by borispovod** [comment]
Hey, 

Not sure the question is clear for me. 

You can look how struct looks if you request it directly from API - [link](https://fullnode.mainnet.aptoslabs.com/v1/accounts/0x05a97986a9d031c4567e15b797be516910cfcb4156312482efc6a19c0a30c948/resource/0x190d44266241744264b964a37b8f09863167a12d3e70cda39376cfb4e3561e12::liquidity_pool::LiquidityPool%3C0x5e156f1207d0ebfa19a9eeff00d62a282278fb8719f4fab3a586a0a2c0fffbea::coin::T,0xcc8a89c8dce9693d354449f1f73e60e14e347417854f029db5bc8e7454008abb::coin::T,0x190d44266241744264b964a37b8f09863167a12d3e70cda39376cfb4e3561e12::curves::Uncorrelated%3E).

And maybe try to convert in the same way.

**Comment by crazybits** [comment]
API returned value are json format,  actually, i would like to know how the LiquidityPool struct(with generic and phantom type) save on Aptos state DB, if i wanner deserialize LiquidityPool from raw bytes into Rust struct, how to define the Rust struct of the LiquidityPool?

**Comment by borispovod** [comment]
@crazybits i think you have to look into Aptos code base and BCS (Binary Canonical Serialization).

**Comment by crazybits** [comment]
already solved the problem ,case closed, thanks
