### ISSUE TITLE
can not click on Petra wallet

### ISSUE THREAD

**Issue by viponedream** [pontem-network/liquidswap#129]
when i bridge in the https://bridge.liquidswap.com/
after connect wallet
APPROVE can not  click
![2X(ELHOW(M8{~9CL876LZQN](https://user-images.githubusercontent.com/16624529/199364622-1c231cb8-c97f-47de-ba2f-8eb02c3dea45.png)

**Comment by borispovod** [comment]
Hey @viponedream ,

We are not maintaining Petra wallet and LayerZero bridge, so passed to Aptos team and LayerZero team.

**Comment by borispovod** [comment]
Aptos deploying fix - https://github.com/aptos-labs/aptos-core/issues/5298.
So i'm closing it.
