### ISSUE TITLE
Liquidswap LayerZero Bridge

### ISSUE THREAD

**Issue by kchain-solutions** [pontem-network/liquidswap#131]
Hello,

I'm a developer and would like to know more about how Liquidswap and Layerzero work.

Has the bridge contract already been published?

Many thanks,
Valerio

**Comment by borispovod** [comment]
Hey,

LayerZero publishing contracts themself, so you probably should look at it in their Github.

**Comment by kchain-solutions** [comment]
Hey Boris,

Many thanks for the reply. I wrote here because I would like to know more about a real working integration and how you use the LayerZero protocol with Aptos contracts. 

I've tried asking the LayerZero team, but documentation with Aptos is a work in progress.

Any information you can give me will be beneficial to me.

PS If you need any support, I would like to be helpful to the Pontem community.

**Comment by borispovod** [comment]
Closing for now
