### ISSUE TITLE
Getting {"Error": "Unexpected error: Unable to resolve packages for package 'my_package_name'" }  when running aptos move test

### ISSUE THREAD

**Issue by f0kes** [pontem-network/liquidswap#134]
Here is my Move.toml file. 
```
[package]
name = 'my_package_name'
version = '1.0.0'

[dependencies.Liquidswap]
git = 'https://github.com/pontem-network/liquidswap.git'
rev = 'main'

[dependencies.LiquidswapRouterV2]
git = 'https://github.com/pontem-network/liquidswap.git'
subdir = 'liquidswap_router_v2/'
rev = 'main'

[dependencies.LiquidswapLP]
git = 'https://github.com/pontem-network/liquidswap.git'
subdir = 'liquidswap_lp/'
rev = 'main'

[addresses]
source_addr = "0xcafe"
#source_addr = "_"

```

Referencing liquidswap locally doesn't help either.

**Comment by f0kes** [comment]
Cloning your repository in a new and attempting to run "aptos move test" there leads to the same result. Same results on different machines. I am running aptos CLI through WSL ubuntu on both machines. Everything works when the only dependency I have is aptos framework.

**Comment by borispovod** [comment]
Hey @f0kes 

Can you try Aptos CLI 1.0.0? We know there is bug in CLI 1.0.1 with resolving dependencies, already discussed with Aptos team.

**Comment by f0kes** [comment]
Thank you for your answer, it does indeed work as expected with Aptos CLI 1.0.0
