### ISSUE TITLE
pay_flashloan lp check bug?

### ISSUE THREAD

**Issue by kr4rk** [pontem-network/liquidswap#140]
In ```liquidswap::liquidity_pool::pay_flashloan``` you check lp change with wrong ```x_res_new_after_fee``` and ```y_res_new_after_fee``` as far as I understand it. Or am I wrong?

You use ```liquidswap::liquidity_pool::new_reserves_after_fees_scaled``` which is designed to calc reserves for swap but not for loan returns.
In that function you substract fee from current reserve but for loan return you should add ```x_in_val``` and ```y_in_val``` to the current reserve since they allready contain the fee.

**Comment by borispovod** [comment]
Hey,

Can you please share more context?

So far i can't confirm. 
The logic of swap or flashloan are pretty same and they both require user to pay fees.

> In that function you substract fee from current reserve

In `pay_flashloan` we calculate `x_res_new_after_fee` and `y_res_new_after_fee` using current reserves (after paid loan). Yes, we remove fees, but we remove fees from the final amount of X and Y reserves after loan paid.

After that we compare that with old `X*Y`.

Example in pseudo-code contains same logic, this one would never work as fees are not paid:

```
# Flashloan test

FEE_SCALE = 10 000
FEE = 30

x_reserve = 12 300 000
y_reserve = 52 300 000 000

# Loan

x_loan = 5 000 000
y_loan = 1 200 000 000

x_reserve = x_reserve  − x_loan
y_reserve = y_reserve − y_loan

# Return of loan (uncorrelated curve)

x_in_val = 5 000 000
y_in_val = 1 200 000 000

x_reserve_size = x_reserve + x_in_val
y_reserve_size = y_reserve + y_in_val

x_pool_size = x_reserve + x_in_val
y_pool_size = y_reserve + y_in_val

x_res_after_fees = x_pool_size × FEE_SCALE − x_in_val × FEE
y_res_after_fees = y_pool_size × FEE_SCALE − y_in_val × FEE

lp_value_before_swap = x_reserve_size × y_reserve_size × (FEE_SCALE × FEE_SCALE)
lp_value_after_swap_and_fee = x_res_after_fees × y_res_after_fees

# Negative result, failed
lp_value_after_swap_and_fee − lp_value_before_swap
```

**Comment by borispovod** [comment]
I awaited more context, closing for now
You are welcome to reopen if something

**Comment by kr4rk** [comment]
@borispovod Thx for your help. Yes I looked into your flash loan tests and saw my fault. Thx for the pseudo code!
