### ISSUE TITLE
Bridge liquidswap - exceeds allowance

### ISSUE THREAD

**Issue by Azazel020** [pontem-network/liquidswap#145]
Situation:

Bridge USDC from Avalanche to USDC Aptos Network using https://bridge.liquidswap.com/

Pushing the button `TRANSFER` ends in a transaction failed, see attachment.

Not clear for the user how to increase this allowance and continue transfering the funds.

![bridge liquidswap](https://github.com/pontem-network/liquidswap/assets/44430967/c5bbc3b6-9356-4802-8b88-7a57850c2cad)

[
![bridge liquidswap 2](https://github.com/pontem-network/liquidswap/assets/44430967/578a3096-3dd7-4d8f-9ad8-5244a2e4cf41)
](url)

**Comment by borispovod** [comment]
This is LayerZero bridge, i think you better contact them. 
Yet so far it seems you first should send allowance transaction for your ERC20 token and only after that transaction confirmed - do a bridge transfer itself. 

Closing for now
